auth0-extensions/auth0-delegated-administration-extension

package.json
server/index.js

✏️ Changes
Added option to exclude admin's accessToken from idToken as a temporary solution of DAE 3.0 security.
We need to publish these:
https://github.com/auth0-extensions/auth0-extension-tools/pull/14
https://github.com/auth0-extensions/auth0-extension-express-tools/pull/15
before merging.
🔗 References
Jira: https://auth0team.atlassian.net/browse/KEY-159
🎯 Testing
✅ This has been tested locally
✅ This has been tested in a webtask

no admin's access tokens on frontend

---

package.json
server/routes/users.js
webtask.json

Removed `SEARCH_ENGINE` option. Force v2 for appliances and v3 for cloud.
Slack Channel: https://auth0.slack.com/archives/CAYKL0SLU/p1535568799000100
Deprecation Case: https://auth0team.atlassian.net/wiki/spaces/DEP/pages/124682419/Deprecation+Case+User+Search+v2+ElasticSearch
Jira: https://auth0team.atlassian.net/browse/KEY-262
✅ This change has integration test coverage
In order to verify that the deployment was successful we will test manually via smoke test.
We will rollback if we find an error during the smoke test.
Deploy a new patch-level update with reverted changes
**Note to reviewers:** ensure that this change is compatible …

Search engine v2 deprication

---

server/lib/getScopes.js
tests/server/lib/getScopes.tests.js

✏️ Changes
With "Enable Legacy Profile" flag disabled, customer cannot set `user.roles` in the rule.
We're adding another option, which allows us to add roles to the namespaced claims of `idToken`.
Here's PR for docs: https://github.com/auth0/docs/pull/6521
🔗 References
Jira: https://auth0team.atlassian.net/browse/KEY-139
🎯 Testing
✅ This has been tested locally
✅ This has been tested in a webtask
✅ This change has unit tests

Namespaced roles

---

client/components/Users/UserActions.jsx
tests/client/components/Users/UserActions.tests.js

"Change Password" and "Reset Password" actions were visible even with `password` field disabled.
Now those actions will be hidden if `password` is disabled in the settings hook. 
Github issue: #115 
Jira: https://auth0team.atlassian.net/browse/KEY-240

Hide actions for disabled fields

---

server/routes/users.js
tests/server/routes/users.tests.js

There was a bug in custom fields search. Search engine v3 does not work with quotes and wildcard character, but v2 - does. These changes meant to fix that bug by using quotes for search engine v2 (`email:"*@gmail.com`), and remove them for search engine v3 (`email:*@gmail.com`).
Slack: https://auth0.slack.com/archives/C9170558S/p1537813879000100

Custom fields search bug fix

---

server/routes/html.js
tests/server/routes/html.tests.js
webtask.json

This PR contains all the changes from #120. The only difference is that now `FAVICON_PATH` secret is exposed in `webtask.json`, so customer can manage it from the extension gallery.
Jira: https://auth0team.atlassian.net/browse/KEY-277

Custom favicon option

---

.circleci/config.yml

`CC_TEST_REPORTER_ID` moved from circle script to dashboard to make config file more portable.

Move Code Climate Reporter Id to Circle dashboard env var

---

.circleci/config.yml

Reverts auth0-extensions/auth0-delegated-administration-extension#139
Reason: moving the env var to circle prevents us from passing it in to forked builds. This does not allow us to be able to run coverage reports on forked pull requests.

Revert "Move Code Climate Reporter Id to Circle dashboard env var"

---

CHANGELOG.md
client/containers/Users/Dialogs/EmailChangeDialog.jsx
client/containers/Users/Dialogs/PasswordChangeDialog.jsx
client/containers/Users/Dialogs/PasswordResetDialog.jsx
client/containers/Users/Dialogs/UsernameChangeDialog.jsx
client/utils/useDefaultFields.js
server/routes/users.js
tests/client/containers/Users/Dialogs/EmailChangeDialog.tests.js
tests/client/containers/Users/Dialogs/PasswordChangeDialog.tests.js
tests/client/containers/Users/Dialogs/PasswordResetDialog.tests.js
tests/client/containers/Users/Dialogs/UsernameChangeDialog.tests.js
tests/client/utils/useDefaultFields.tests.js

The disabled `Connection` field in `Change*` dialogs was broken and didn't display connection name. Fixed by adding connections name to the user object, where redux-form can access its value.
Added check for total connections number, to hide the `Connection` field, if there is only one connection exists.
One connection:
Two connections:
Jira: https://auth0team.atlassian.net/browse/KEY-688
GH Issue: #155 

Connection field proper hiding / showing

---

CHANGELOG.md
server/routes/users.js
tests/server/routes/users.tests.js

Now extension will use `deleteMultifactorProvider` only for supported providers (duo/google), and `removeGuardian` for any other providers.
Slack: https://auth0.slack.com/archives/C9170558S/p1547102000093500

fixed removeMfa to handle any non-duo/google provider

---

CHANGELOG.md
package-lock.json
package.json
server/routes/users.js
webtask.json

In recent update `canCreateUsers` flag was added to the `settings` object, but there was no check for object to exist. Added empty object as a default value for `settings` in these changes. 
Support ticket: https://auth0.lightning.force.com/lightning/r/Case/5001G00000bu3KTQAY/view

Empty settings bug fix (user creation)

---

CHANGELOG.md
client/actions/user.js

Due to bug, it was impossible to override `client` field for `reset password` action using `userFields`. Fixes #154
Github: #154

Password reset fix

---

CHANGELOG.md
client/actions/auth.js
server/index.js
server/lib/config.js
server/lib/getApiToken.js
server/lib/removeGuardian.js
server/lib/userBlocks.js
server/routes/api.js
server/routes/hooks.js
server/routes/html.js
server/routes/users.js
tests/server/lib/config.tests.js
webtask.json

`AUTH0_ISSUER_DOMAIN` secret has been exposed in the webtask.json. This secret can be used instead of AUTH0_DOMAIN to support custom domains.
✅ This change has been tested in a Webtask (including appliance with custom domain)
✅ Can be deployed now.

custom domains support

---

CHANGELOG.md
package-lock.json
package.json
server/routes/users.js
tests/server/routes/users.tests.js
tests/utils/dummyData.js
webtask.json

DAE does not allow users to remove MFA, if the enrollment wasn't confirmed. Checking all enrollments on user request should fix this issue.
Jira: https://auth0team.atlassian.net/projects/ESD/queues/custom/321/ESD-320

Allow removing unconfirmed MFA enrollments

---

server/routes/applications.js
server/routes/connections.js
tests/server/routes/applications.tests.js
tests/server/routes/connections.tests.js
tests/utils/dummyData.js

Some server-side endpoints were returning extra information not used by the extension.
A customer reported that this information is sensitive and must be removed - this PR fixes that.
I changed:
1. `/applications` endpoint to return only `client_id, name`
2. `/connections` endpoint to return only `id, name, strategy, options.requires_username`
Added unit tests to ensure that any extra fields are removed from initial data.
To test this change, ensure that any application and connection-related functionality works correctly. For example:
1. Applications are used during password reset - try to send a password reset email.
2. Connections are used during user creation - try to create a user having several connections with different combinations of settings, especially some requiring username …

Fixed extra information leak for connections and applications

---

client/components/Users/UserActions.jsx
client/components/Users/UserFieldsChangeForm.jsx
client/constants.js
tests/client/components/Users/UserActions.tests.js
tests/client/components/Users/UserFieldsChangeForm.tests.js

Customer reported that reserved fields like passwordReset are being rendered in custom fields change form - this must be removed as these fields control the display of user menu actions, but bust not be rendered as custom fields.
In this PR, the "reserved" fields were extracted into external constants and reused in UserActions component to filter out any input custom fields.
No new unit tests were added for UserActions - I am not sure how to test it. To test the actual functionality it requires a settings query hook like the following:
```
function(ctx, callback) {
return callback(null, {
userFields: [ {
property: "resetPassword",
edit: true,
display: false
}, {
property: "password",
edit: false
}  ]
});
}
```
Then the fields in the hook above must not be rendered in Custom Fields edit …

Fix to remove rendering of reserved fields in custom field edit form

---

CHANGELOG.md
package-lock.json
package.json
server/routes/api.js
webtask.json

The extension fails to authenticate user if custom domain is enabled (PSaaS) because it expects custom domain to be issuer, but in case of PSaaS, the issuer is always original domain. Fixed by checking `IS_APPLIANCE`.
Jira: https://auth0team.atlassian.net/projects/ESD/queues/custom/321/ESD-1097
These changes only affects appliances

fixed permissions check for psaas with custom domain

---

client/actions/user.js
client/containers/Users/Dialogs/PasswordResetDialog.jsx
package-lock.json
server/routes/users.js
tests/client/containers/Users/Dialogs/PasswordResetDialog.tests.js

This removes an unnecessary "Client" option from the password reset dialog. The `client_id` is not required (or even an argument for) the `requestChangePasswordEmail` method in node-auth0:
https://github.com/auth0/node-auth0/blob/v2.13.0/src/auth/index.js#L436

AUTHZ-1338 - Remove Client option from password reset dialog

---

client/containers/Users/Users.styles.css

This PR fixes an overflow issue where custom select components had issues rendering beyond the modal container. This was causing issues for customers using custom fields and not able to select beyond a certain number of options.
**Before**
**After**
https://github.com/auth0-extensions/auth0-delegated-administration-extension/issues/201

Fix modal overflow issues

---

client/actions/user.js
client/containers/Users/Dialogs/PasswordResetDialog.jsx
client/utils/useDefaultFields.js
server/routes/users.js
tests/client/containers/Users/Dialogs/PasswordResetDialog.tests.js

This PR introduces the client option back to the password reset dialog. It is optional.
**Before:**
**After:**
PW Reset Request in the logs w/ and wo/ selecting a client:
Two different PW reset emails due to different client chosen:
HTTP requests to the extension w/ and wo/ selecting a client on the UI:
https://auth0team.atlassian.net/browse/ESD-3554 
https://github.com/auth0-extensions/auth0-delegated-administration-extension/pull/200
✅This change has unit test coverage
✅This can be deployed any time
In order to verify that the deployment was successful we will see the optional client selection on the PW reset modal. …

ESD-3554 - Add optional client option to password reset dialog

---

CHANGELOG.md
client/actions/auth.js
package-lock.json
package.json
webtask.json

The originating error is caused due to a flag called IS_APPLIANCE which is activated for PSaaS deployments. This flag works around the disparity between the PSaaS legacy custom domains implementation - namely, the token issuer being auth0 rather than the customer's custom domain. Once a PSaaS environment migrates to achieve parity with Auth0's public environment's custom domains implementations, the work around in the extension gets triggered and causes the extension to fail to load, since migrating allows the token issuer to be set correctly.
For more context, you can check the internal proposal doc.
https://auth0team.atlassian.net/wiki/spaces/Bacca/pages/459833612/Removing+IS+APPLIANCE+flag+for+legacy+custom+domains  
This is a front end change, so I tested it locally. Seems to work …

[AUTHZ-1382] remove support for psaas legacy custom domains

---

CHANGELOG.md
package-lock.json
package.json
server/routes/users.js
tests/server/routes/users.tests.js
webtask.json

Always retrieve MFA status. 
Fixes: "Remove MFA" functionality was missing for users that enrolled with MFA but never logged in.
https://auth0team.atlassian.net/browse/AUTHZ-1470 (internal ticketing, for auziro eyes only)
1. Enable MFA for your tenant:
2. Go to a user and send an enrollment link.  Please use a **database connection user** to test.
3. Enroll but **don’t login**.
4. On management dashboard, verify that there is a reset mfa button visible:
5. On DAE, Remove MFA is visible, too. Verify it works.
Previously, no button was visible on Step (5).
✅This change has unit test coverage
✅This can be deployed any time
In order to verify that the deployment …

AUTHZ-1470 - Always retrieve MFA status

---

server/routes/api.js

Custom domains in appliance was not working (reported by a customer). The appliance has some settings that are different from cloud which made it difficult to troubleshoot.
Issue:
- auth0 SDK on the front end side is configure with the custom domain - https://github.com/auth0-extensions/auth0-delegated-administration-extension/blob/master/client/actions/auth.js#L7-L13
- the authentication middleware was not configured to use the custom domain - https://github.com/auth0-extensions/auth0-delegated-administration-extension/blob/master/server/routes/api.js#L71
That mismatch configuration was causing the extension to fail to authenticate the user, throwing the reported error here - https://github.com/mcastany/auth0-delegated-administration-extension/blob/master/server/lib/middlewares/requireSco …

Fix issue with custom domains in appliance

---

server/routes/users.js
webtask.json

Expose user search engine to allow private versions select the search they are using. By default use search v3
✅This change has been tested in a Webtask
✅This can be deployed any time

Expose user search engine

---

client/actions/user.js
client/constants.js
client/containers/Users/Users.jsx
client/utils/useDefaultFields.js
package.json
server/lib/multipartRequest.js
server/routes/connections.js
tests/client/components/Users/UserForm.tests.js
tests/client/utils/useDefaultFields.tests.js

With this PR user creation modal box switches between a select and an input based on how many connections are there in a tenant. If too much, instead of listing them all we switch to a text field in which you can type the connection name.
When < threshold:
When > threshold:
https://auth0team.atlassian.net/browse/IDS-4707
Reduce `CONNECTIONS_FETCH_LIMIT` to something low to be able to test it. Run DAE locally, setting up against the deployment of your choice. 
See once the CONNECTIONS_FETCH_LIMIT is exceeded:
1. A textbox to provide connection name.
2. Optional user name area.
See once the CONNECTIONS_FETCH_LIMIT is not exceeded:
1. A select-box listing connection names to choose from.
2. Mandatory user name area only if connection requires a username.
Additionally see:
1. Only a single …

IDS-4707 - Switch from InputCombo to InputText if there are too many connections to list

---

.circleci/config.yml

- The deploy step in the CI doesn't work, because it replies on a heroku app which is no longer functional. This PR removes the deploy step from the Circle CI config.
- part of tidy up from https://auth0team.atlassian.net/browse/IDS-4707
✅ This PR can be tested by observing if the `build_and_test` CI workflow still works
In order to verify that the deployment was successful we will check the CI on this PR
We won't roll back because what was removed was already broken

Remove deploy step from CI

---

package.json
server/lib/logger.js
webtask.json

- Changed winston log level back to 'debug'
https://auth0team.atlassian.net/browse/IDS-5332
Tested in a dev space and checked in the realtime webtask log extension that the debug logs are being shown again
In order to verify that the deployment was successful we will check the extension logs in production.
We will rollback if there's any issues with the extension
Revert commit and upload a new patch version of the extension.

fix: [IDS-5332] Change log level back to 'debug'

---

client/actions/auth.js

- Increased the timeout for the request to `/me` from 5s to 8s
Some users with the admin role don't see the admin actions (like the "Configuration" tab on first load because this request was timing out.
https://auth0team.atlassian.net/browse/IDS-5562
Just a number change, no actual functional changes.
Will be tested together with the node 22 update before releasing the new extension version.
> or
> ⚠️ This should not be merged until:
> - Other PR is merged because REASON
> - After date because REASON
> - Other condition: REASON
> Explain how the change will be verified once released. Manual …

feat: [IDS-5562] Increase timeout for /me request in frontend

---

tools/cdn.sh

Fix bundle upload script. The bundle should be named `auth0-delegated-admin-<VERSION>.js` instead of `auth0-delegated-admin.extension.<VERSION>.js`
https://auth0team.atlassian.net/browse/IDS-5630
Tested manually using my own s3 bucket.   
> Can this change be merged at any time? What will the deployment of the change look like? Does this need to be released in lockstep with something else?
In order to verify that the deployment was successful we will back-up s3 assets and run this script.
> Explain when and why we will rollback the change.
If script does not work properly - we will remove …

fix: bundle upload script
