auth0-extensions/auth0-delegated-administration-extension

client/components/Users/UserForm.jsx, client/containers/Users/Users.jsx, server/lib/scriptmanager.js, server/routes/api.js, server/routes/connections.js, tests/server/routes/connections.tests.js, tests/utils/dummyData.js
- filtering connections by settings
- show connections select only if there are more than one connection
- hide create button if no connections found
- unit tests for connections router
=> Connections filtering

client/actions/script.js, client/components/Editor/index.js, client/components/Users/UserForm.jsx, client/components/Users/UserInfo.jsx, client/containers/Configuration/Configuration.jsx, client/containers/Users/Users.css, client/containers/Users/Users.jsx, client/reducers/scripts.js
- scripts update fixed
- username field added to user info page
- memberships dropdown fixed
=> Final fixes

server/routes/users.js, tests/server/routes/connections.tests.js, tests/server/routes/users.tests.js, tests/utils/dummyData.js
- check ids before delete
- tests added
=> disallow user to delete himself

.vscode/settings.json, client/components/Users/UserOverview.jsx, client/components/Users/UserPaginator.jsx, client/components/Users/index.js, client/containers/Users/Users.jsx, client/reducers/users.js
=> Add users pagination

package.json, yarn.lock
Fixes an IE11 scrolling issue on a multi select field.
=> update auth0-extension-ui version

client/actions/auth.js, client/app.jsx, client/components/Users/UsersTable.jsx, client/containers/App.jsx, client/containers/Login.jsx, client/containers/RequireAuthentication.jsx, client/reducers/languageDictionary.js
This allows someone to link someone over to the DAE with a locale, so they can default the login page to the right locale. 
There is also a little cleanup of some localization changes that broke things.
=> Add locale to login page

server/routes/users.js, webtask.json
```
function filterHook (ctx, callback) {
...
const filter = {
query: '...',
searchEngine: 'v2' // 'v3' by default
};
callback(null, filter);
}
```
=> Search engine v3 for DAE v2.x

.gitignore, client/actions/auth.js, client/components/Users/LuceneSearchBar.jsx, client/components/Users/UserActions.jsx, client/components/Users/UserOverview.jsx, client/containers/Users/Users.jsx, tests/server/lib/scriptmanager.tests.js
✏️ Changes
This PR contains changes from #104 
But with `admins/login` fix.
🔗 References
Slack: https://auth0.slack.com/archives/C9170558S/p1529959475000450
🎯 Testing
✅ This has been tested locally
=> Admins login fix

client/actions/user.js, client/components/Users/UserActions.jsx, client/containers/Users/Dialogs/RemoveMultiFactorDialog.jsx, client/utils/useDefaultFields.js, package.json, server/routes/users.js, tests/server/routes/users.tests.js, webtask.json, yarn.lock
https://auth0team.atlassian.net/browse/KEY-201
=> Fix functionality to remove MFA

client/components/Users/UserInfo.jsx, package.json, tests/client/components/Users/UserInfo.tests.js
Added a default display function for `Multifactor` field.
Fixes #110 
Jira: https://auth0team.atlassian.net/browse/KEY-222
✅ This has been tested locally
✅ This has been tested in a webtask
✅ This change has been acceptance tested
✅ This change has been manually smoke tested
🚫 This change can support multiple releases of the code serving traffic at the same time
✅ This can be deployed any time because it has no prerequisites.
✅ The change will be available to the complete environment at once
🚫 The change is behind a feature flag and will go through a percentage based rollout process
🚫 The change is behind a flag and customers will opt-in to the change
In order to verify that the deployment was successful we will update the extensions via a test tenant …
=> Default MFA display function

.circleci/config.yml, README.md, client/components/Users/UserFormField.jsx, package.json, yarn.lock
UI dependency package updated. Update consists of showing placeholder for a select element when options count is 1 or more.
https://auth0.zendesk.com/agent/tickets/48075
When there is a single client, resetting the user password should default to `Please select...`. 
In order to verify that the deployment was successful we will run the test case after deployed.
We will rollback if the UI shows side effects.
Remove the S3 files.
**Note to reviewers:** ensure that this change is compatible with the Appliance.
=> ZD-48075: Reset password client drop down should show placeholder

.circleci/config.yml
CI upgrade (application code was not changed)
=> Update circle to use workflow.

.circleci/config.yml, CHANGELOG.md
- Updated CI script to pull release notes from changelogs.
=> Create Release notes from changelogs.

README.md
Readme Update
[Zendesk](https://auth0.zendesk.com/agent/tickets/48862)
=> Make Readme a bit clearer for local development.

CHANGELOG.md, client/components/Users/UserActions.jsx, client/utils/display.js, tests/server/routes/users.tests.js
First of all, display function of userFields `edit` didn't work at all. These changes meant to execute `edit.display` function for each field before rendering form.
Second - general display function didn't have `value` argument. `Value` is added as second argument (as in docs), which is moving `dictionary` object to third param. So this is kind of a breaking changes.
Jira: https://auth0team.atlassian.net/browse/KEY-320
=> Display functions fix

.circleci/config.yml, README.md, package.json
- Add Code Climate badges (coverage and maintainability)
- Remove codecov from circle script
- Tested failure PR at #137
=> KEY-345: Remove codecov io

.circleci/config.yml
This PR enabled the building and deployment of review apps for the delegated admin extension
=> Enable review app deploys in CircleCI

CHANGELOG.md, package-lock.json, package.json, webtask.json
Reverts auth0-extensions/auth0-delegated-administration-extension#149
=> Revert "Deep Dive: Update moment.js"

CHANGELOG.md, client/utils/logTypes.js
Added missing log types (i wish we could just request those from api2 or something). 
Jira: https://auth0team.atlassian.net/browse/KEY-578
Github: #148 
=> KEY-578: Missing log types

CHANGELOG.md, index.js, package-lock.json, package.json, server/index.js, server/lib/middlewares/requireScope.js, server/lib/middlewares/verifyUserAccess.js, webtask.js, webtask.json
Fixed `PUBLIC_WT_URL`. This change is required to run extensions in stage2.
Jira: https://auth0team.atlassian.net/projects/ESD/queues/custom/321/ESD-158
=> PUBLIC_WT_ULR fix for stage2

.circleci/config.yml
Will add FOSSA analysis checks to circleci during build.
https://auth0team.atlassian.net/browse/DXEX-99
=> Add FOSSA Compliance checks during Build

.circleci/config.yml
- Replaces build container with auth0 supported build container.
- Removes creating github release from chandler.
=> Streamline Release Process

client/actions/auth.js
=> fix custom domain logout

client/utils/logTypes.js
Add the logtype `ferrt` - _reused refresh token_.
=> Add the logtype `ferrt` - Reused Refresh Token

CHANGELOG.md, package-lock.json, package.json
Update changelog before release
=> Updated changelog
